### ISSUE TITLE
Planetscale does not allow insecure connection error message

### ISSUE THREAD

**Issue by ghost** [mattddean/t3-app-router-edge-drizzle#7]
Error message:

pnpm db:push
> t3-app-router-edge-drizzle@0.1.0 db:push D:\nextjs\t3-app-router-edge-drizzle
> pnpm drizzle-kit push:mysql
drizzle-kit: v0.17.1
drizzle-orm: v0.23.2-ec4bb7f

No config path provided, using default 'drizzle.config.ts'
Reading config file 'D:\nextjs\t3-app-router-edge-drizzle\drizzle.config.ts'
D:\nextjs\t3-app-router-edge-drizzle\node_modules\.pnpm\drizzle-kit@0.17.1-5df459e\node_modules\drizzle-kit\index.js:43677
      const createConnectionErr = new Error();
                                  ^

Error: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS

Resolved by appending "ssl={"rejectUnauthorized":true}" to the DATABASE_URL
Worked for me

**Comment by mattddean** [comment]
The .env.example file's DB_URL contains this suffix. Feel free to open a PR to add a comment to that file above the DB_URL variable if you feel it isn't clear enough.
